import { NextResponse } from "next/server";
import prisma from "@/lib/prisma";

// Toutes les traductions GLOBALES pour 26 langues
const TRANSLATIONS: Record<string, Record<string, string>> = {
  // NAVIGATION
  "nav.studio": { FR: "Studio", EN: "Studio", DE: "Studio", ES: "Estudio", IT: "Studio", PT: "Estúdio", NL: "Studio", PL: "Studio", RU: "Студия", JA: "スタジオ", ZH: "工作室", KO: "스튜디오", AR: "الاستوديو", TR: "Stüdyo", SV: "Studio", DA: "Studio", FI: "Studio", NO: "Studio", CS: "Studio", EL: "Στούντιο", HU: "Stúdió", RO: "Studio", SK: "Štúdio", BG: "Студио", UK: "Студія", ID: "Studio" },
  "nav.dashboard": { FR: "Tableau de bord", EN: "Dashboard", DE: "Dashboard", ES: "Panel de control", IT: "Pannello", PT: "Painel", NL: "Dashboard", PL: "Panel", RU: "Панель", JA: "ダッシュボード", ZH: "仪表板", KO: "대시보드", AR: "لوحة التحكم", TR: "Panel", SV: "Instrumentpanel", DA: "Dashboard", FI: "Hallintapaneeli", NO: "Dashbord", CS: "Přehled", EL: "Πίνακας", HU: "Irányítópult", RO: "Panou", SK: "Prehľad", BG: "Табло", UK: "Панель", ID: "Dasbor" },
  "nav.settings": { FR: "Paramètres", EN: "Settings", DE: "Einstellungen", ES: "Configuración", IT: "Impostazioni", PT: "Configurações", NL: "Instellingen", PL: "Ustawienia", RU: "Настройки", JA: "設定", ZH: "设置", KO: "설정", AR: "الإعدادات", TR: "Ayarlar", SV: "Inställningar", DA: "Indstillinger", FI: "Asetukset", NO: "Innstillinger", CS: "Nastavení", EL: "Ρυθμίσεις", HU: "Beállítások", RO: "Setări", SK: "Nastavenia", BG: "Настройки", UK: "Налаштування", ID: "Pengaturan" },
  "nav.logout": { FR: "Se déconnecter", EN: "Log out", DE: "Abmelden", ES: "Cerrar sesión", IT: "Disconnetti", PT: "Sair", NL: "Uitloggen", PL: "Wyloguj", RU: "Выйти", JA: "ログアウト", ZH: "登出", KO: "로그아웃", AR: "تسجيل الخروج", TR: "Çıkış", SV: "Logga ut", DA: "Log ud", FI: "Kirjaudu ulos", NO: "Logg ut", CS: "Odhlásit", EL: "Αποσύνδεση", HU: "Kijelentkezés", RO: "Deconectare", SK: "Odhlásiť", BG: "Изход", UK: "Вийти", ID: "Keluar" },
  "nav.actions": { FR: "Actions", EN: "Actions", DE: "Aktionen", ES: "Acciones", IT: "Azioni", PT: "Ações", NL: "Acties", PL: "Akcje", RU: "Действия", JA: "アクション", ZH: "操作", KO: "작업", AR: "الإجراءات", TR: "İşlemler", SV: "Åtgärder", DA: "Handlinger", FI: "Toiminnot", NO: "Handlinger", CS: "Akce", EL: "Ενέργειες", HU: "Műveletek", RO: "Acțiuni", SK: "Akcie", BG: "Действия", UK: "Дії", ID: "Tindakan" },
  "nav.manageQuizzes": { FR: "Gérer les Quizz", EN: "Manage Quizzes", DE: "Quiz verwalten", ES: "Gestionar tests", IT: "Gestisci quiz", PT: "Gerenciar testes", NL: "Quizzen beheren", PL: "Zarządzaj testami", RU: "Управление тестами", JA: "クイズ管理", ZH: "管理测验", KO: "퀴즈 관리", AR: "إدارة الاختبارات", TR: "Sınavları Yönet", SV: "Hantera frågesporter", DA: "Administrer quizzer", FI: "Hallitse visailuja", NO: "Administrer quizer", CS: "Spravovat kvízy", EL: "Διαχείριση κουίζ", HU: "Kvízek kezelése", RO: "Gestionare chestionare", SK: "Spravovať kvízy", BG: "Управление на тестове", UK: "Керування тестами", ID: "Kelola Kuis" },
  "nav.levelsScale": { FR: "Échelle des niveaux", EN: "Levels Scale", DE: "Stufenskala", ES: "Escala de niveles", IT: "Scala dei livelli", PT: "Escala de níveis", NL: "Niveauschaal", PL: "Skala poziomów", RU: "Шкала уровней", JA: "レベルスケール", ZH: "等级量表", KO: "레벨 스케일", AR: "مقياس المستويات", TR: "Seviye Ölçeği", SV: "Nivåskala", DA: "Niveauskala", FI: "Tasoasteikko", NO: "Nivåskala", CS: "Stupnice úrovní", EL: "Κλίμακα επιπέδων", HU: "Szintskála", RO: "Scara nivelurilor", SK: "Stupnica úrovní", BG: "Скала на нивата", UK: "Шкала рівнів", ID: "Skala Level" },
  
  // HEADER
  "header.mySites": { FR: "Mes sites", EN: "My sites", DE: "Meine Websites", ES: "Mis sitios", IT: "I miei siti", PT: "Meus sites", NL: "Mijn sites", PL: "Moje strony", RU: "Мои сайты", JA: "マイサイト", ZH: "我的网站", KO: "내 사이트", AR: "مواقعي", TR: "Sitelerim", SV: "Mina webbplatser", DA: "Mine sider", FI: "Omat sivustot", NO: "Mine nettsteder", CS: "Moje weby", EL: "Οι ιστοσελίδες μου", HU: "Webhelyeim", RO: "Site-urile mele", SK: "Moje stránky", BG: "Моите сайтове", UK: "Мої сайти", ID: "Situs Saya" },
  "header.mySitesDescription": { FR: "Gérez vos sites d'accompagnement IA", EN: "Manage your AI coaching sites", DE: "Verwalten Sie Ihre KI-Coaching-Websites", ES: "Gestiona tus sitios de IA", IT: "Gestisci i tuoi siti di coaching IA", PT: "Gerencie seus sites de coaching de IA", NL: "Beheer uw AI-coachingsites", PL: "Zarządzaj stronami coachingu AI", RU: "Управляйте сайтами AI-коучинга", JA: "AIコーチングサイトを管理", ZH: "管理您的AI辅导网站", KO: "AI 코칭 사이트 관리", AR: "إدارة مواقع التدريب على الذكاء الاصطناعي", TR: "AI koçluk sitelerinizi yönetin", SV: "Hantera dina AI-coachningswebbplatser", DA: "Administrer dine AI-coaching-sider", FI: "Hallitse AI-valmennussivustojasi", NO: "Administrer dine AI-coaching-nettsteder", CS: "Spravujte weby pro AI koučink", EL: "Διαχειριστείτε τους ιστοτόπους AI coaching", HU: "Kezelje AI coaching webhelyeit", RO: "Gestionați site-urile de coaching AI", SK: "Spravujte stránky AI koučingu", BG: "Управлявайте сайтове за AI коучинг", UK: "Керуйте сайтами AI-коучингу", ID: "Kelola situs pelatihan AI Anda" },
  "header.addSite": { FR: "Ajouter un site", EN: "Add a site", DE: "Website hinzufügen", ES: "Añadir un sitio", IT: "Aggiungi un sito", PT: "Adicionar um site", NL: "Site toevoegen", PL: "Dodaj stronę", RU: "Добавить сайт", JA: "サイトを追加", ZH: "添加网站", KO: "사이트 추가", AR: "إضافة موقع", TR: "Site Ekle", SV: "Lägg till webbplats", DA: "Tilføj side", FI: "Lisää sivusto", NO: "Legg til nettsted", CS: "Přidat web", EL: "Προσθήκη ιστοσελίδας", HU: "Webhely hozzáadása", RO: "Adaugă un site", SK: "Pridať stránku", BG: "Добавяне на сайт", UK: "Додати сайт", ID: "Tambah situs" },
  "header.addPerson": { FR: "Ajouter une personne", EN: "Add a person", DE: "Person hinzufügen", ES: "Añadir una persona", IT: "Aggiungi una persona", PT: "Adicionar uma pessoa", NL: "Persoon toevoegen", PL: "Dodaj osobę", RU: "Добавить человека", JA: "人物を追加", ZH: "添加人员", KO: "사람 추가", AR: "إضافة شخص", TR: "Kişi Ekle", SV: "Lägg till person", DA: "Tilføj person", FI: "Lisää henkilö", NO: "Legg til person", CS: "Přidat osobu", EL: "Προσθήκη ατόμου", HU: "Személy hozzáadása", RO: "Adaugă o persoană", SK: "Pridať osobu", BG: "Добавяне на човек", UK: "Додати людину", ID: "Tambah orang" },
  
  // USER
  "user.accountSettings": { FR: "Paramètres du compte", EN: "Account settings", DE: "Kontoeinstellungen", ES: "Configuración de cuenta", IT: "Impostazioni account", PT: "Configurações da conta", NL: "Accountinstellingen", PL: "Ustawienia konta", RU: "Настройки аккаунта", JA: "アカウント設定", ZH: "账户设置", KO: "계정 설정", AR: "إعدادات الحساب", TR: "Hesap Ayarları", SV: "Kontoinställningar", DA: "Kontoindstillinger", FI: "Tiliasetukset", NO: "Kontoinnstillinger", CS: "Nastavení účtu", EL: "Ρυθμίσεις λογαριασμού", HU: "Fiókbeállítások", RO: "Setări cont", SK: "Nastavenia účtu", BG: "Настройки на акаунта", UK: "Налаштування облікового запису", ID: "Pengaturan akun" },
  "user.becomeAdmin": { FR: "Devenir administrateur", EN: "Become administrator", DE: "Administrator werden", ES: "Convertirse en administrador", IT: "Diventa amministratore", PT: "Tornar-se administrador", NL: "Word beheerder", PL: "Zostań administratorem", RU: "Стать администратором", JA: "管理者になる", ZH: "成为管理员", KO: "관리자 되기", AR: "أصبح مسؤولاً", TR: "Yönetici Ol", SV: "Bli administratör", DA: "Bliv administrator", FI: "Ryhdy ylläpitäjäksi", NO: "Bli administrator", CS: "Stát se správcem", EL: "Γίνε διαχειριστής", HU: "Adminisztrátor lesz", RO: "Devino administrator", SK: "Stať sa správcom", BG: "Стани администратор", UK: "Стати адміністратором", ID: "Jadi administrator" },
  "user.becomeStandard": { FR: "Redevenir standard", EN: "Become standard user", DE: "Standardbenutzer werden", ES: "Volver a usuario estándar", IT: "Torna utente standard", PT: "Voltar a usuário padrão", NL: "Word standaard gebruiker", PL: "Wróć do standardowego", RU: "Стать обычным пользователем", JA: "標準ユーザーに戻る", ZH: "恢复为标准用户", KO: "일반 사용자로 전환", AR: "العودة كمستخدم عادي", TR: "Standart Kullanıcı Ol", SV: "Bli standardanvändare", DA: "Bliv standardbruger", FI: "Palaa tavalliseksi käyttäjäksi", NO: "Bli standardbruker", CS: "Stát se běžným uživatelem", EL: "Γίνε κανονικός χρήστης", HU: "Normál felhasználó lesz", RO: "Devino utilizator standard", SK: "Stať sa bežným používateľom", BG: "Стани стандартен потребител", UK: "Стати звичайним користувачем", ID: "Jadi pengguna standar" },
  "user.administrator": { FR: "Administrateur", EN: "Administrator", DE: "Administrator", ES: "Administrador", IT: "Amministratore", PT: "Administrador", NL: "Beheerder", PL: "Administrator", RU: "Администратор", JA: "管理者", ZH: "管理员", KO: "관리자", AR: "المسؤول", TR: "Yönetici", SV: "Administratör", DA: "Administrator", FI: "Ylläpitäjä", NO: "Administrator", CS: "Správce", EL: "Διαχειριστής", HU: "Adminisztrátor", RO: "Administrator", SK: "Správca", BG: "Администратор", UK: "Адміністратор", ID: "Administrator" },
  "user.standardUser": { FR: "Utilisateur standard", EN: "Standard user", DE: "Standardbenutzer", ES: "Usuario estándar", IT: "Utente standard", PT: "Usuário padrão", NL: "Standaard gebruiker", PL: "Standardowy użytkownik", RU: "Обычный пользователь", JA: "標準ユーザー", ZH: "标准用户", KO: "일반 사용자", AR: "مستخدم عادي", TR: "Standart Kullanıcı", SV: "Standardanvändare", DA: "Standardbruger", FI: "Tavallinen käyttäjä", NO: "Standardbruker", CS: "Běžný uživatel", EL: "Κανονικός χρήστης", HU: "Normál felhasználó", RO: "Utilizator standard", SK: "Bežný používateľ", BG: "Стандартен потребител", UK: "Звичайний користувач", ID: "Pengguna standar" },
  "user.adminCodeTitle": { FR: "Devenir administrateur", EN: "Become administrator", DE: "Administrator werden", ES: "Convertirse en administrador", IT: "Diventa amministratore", PT: "Tornar-se administrador", NL: "Word beheerder", PL: "Zostań administratorem", RU: "Стать администратором", JA: "管理者になる", ZH: "成为管理员", KO: "관리자 되기", AR: "أصبح مسؤولاً", TR: "Yönetici Ol", SV: "Bli administratör", DA: "Bliv administrator", FI: "Ryhdy ylläpitäjäksi", NO: "Bli administrator", CS: "Stát se správcem", EL: "Γίνε διαχειριστής", HU: "Adminisztrátor lesz", RO: "Devino administrator", SK: "Stať sa správcom", BG: "Стани администратор", UK: "Стати адміністратором", ID: "Jadi administrator" },
  "user.adminCodeDescription": { FR: "Entrez le code administrateur pour accéder aux fonctionnalités avancées.", EN: "Enter the administrator code to access advanced features.", DE: "Geben Sie den Administratorcode ein.", ES: "Ingrese el código de administrador.", IT: "Inserisci il codice amministratore.", PT: "Digite o código de administrador.", NL: "Voer de beheerderscode in.", PL: "Wprowadź kod administratora.", RU: "Введите код администратора.", JA: "管理者コードを入力してください。", ZH: "输入管理员代码。", KO: "관리자 코드를 입력하세요.", AR: "أدخل رمز المسؤول.", TR: "Yönetici kodunu girin.", SV: "Ange administratörskoden.", DA: "Indtast administratorkoden.", FI: "Anna ylläpitäjäkoodi.", NO: "Skriv inn administratorkoden.", CS: "Zadejte kód správce.", EL: "Εισάγετε τον κωδικό διαχειριστή.", HU: "Adja meg az adminisztrátori kódot.", RO: "Introduceți codul de administrator.", SK: "Zadajte kód správcu.", BG: "Въведете администраторски код.", UK: "Введіть код адміністратора.", ID: "Masukkan kode administrator." },
  "user.adminCodePlaceholder": { FR: "Code administrateur", EN: "Administrator code", DE: "Administratorcode", ES: "Código de administrador", IT: "Codice amministratore", PT: "Código de administrador", NL: "Beheerderscode", PL: "Kod administratora", RU: "Код администратора", JA: "管理者コード", ZH: "管理员代码", KO: "관리자 코드", AR: "رمز المسؤول", TR: "Yönetici kodu", SV: "Administratörskod", DA: "Administratorkode", FI: "Ylläpitäjäkoodi", NO: "Administratorkode", CS: "Kód správce", EL: "Κωδικός διαχειριστή", HU: "Adminisztrátori kód", RO: "Cod administrator", SK: "Kód správcu", BG: "Администраторски код", UK: "Код адміністратора", ID: "Kode administrator" },
  "user.validate": { FR: "Valider", EN: "Validate", DE: "Bestätigen", ES: "Validar", IT: "Convalida", PT: "Validar", NL: "Valideren", PL: "Zatwierdź", RU: "Подтвердить", JA: "確認", ZH: "验证", KO: "확인", AR: "تأكيد", TR: "Doğrula", SV: "Validera", DA: "Valider", FI: "Vahvista", NO: "Valider", CS: "Potvrdit", EL: "Επικύρωση", HU: "Érvényesítés", RO: "Validare", SK: "Potvrdiť", BG: "Потвърди", UK: "Підтвердити", ID: "Validasi" },
  "user.cancel": { FR: "Annuler", EN: "Cancel", DE: "Abbrechen", ES: "Cancelar", IT: "Annulla", PT: "Cancelar", NL: "Annuleren", PL: "Anuluj", RU: "Отмена", JA: "キャンセル", ZH: "取消", KO: "취소", AR: "إلغاء", TR: "İptal", SV: "Avbryt", DA: "Annuller", FI: "Peruuta", NO: "Avbryt", CS: "Zrušit", EL: "Ακύρωση", HU: "Mégse", RO: "Anulare", SK: "Zrušiť", BG: "Отказ", UK: "Скасувати", ID: "Batal" },
  
  // TABS
  "tabs.team": { FR: "Équipe", EN: "Team", DE: "Team", ES: "Equipo", IT: "Team", PT: "Equipe", NL: "Team", PL: "Zespół", RU: "Команда", JA: "チーム", ZH: "团队", KO: "팀", AR: "الفريق", TR: "Ekip", SV: "Team", DA: "Team", FI: "Tiimi", NO: "Team", CS: "Tým", EL: "Ομάδα", HU: "Csapat", RO: "Echipă", SK: "Tím", BG: "Екип", UK: "Команда", ID: "Tim" },
  "tabs.organization": { FR: "Organisation", EN: "Organization", DE: "Organisation", ES: "Organización", IT: "Organizzazione", PT: "Organização", NL: "Organisatie", PL: "Organizacja", RU: "Организация", JA: "組織", ZH: "组织", KO: "조직", AR: "التنظيم", TR: "Organizasyon", SV: "Organisation", DA: "Organisation", FI: "Organisaatio", NO: "Organisasjon", CS: "Organizace", EL: "Οργανισμός", HU: "Szervezet", RO: "Organizație", SK: "Organizácia", BG: "Организация", UK: "Організація", ID: "Organisasi" },
  "tabs.profile": { FR: "Profil", EN: "Profile", DE: "Profil", ES: "Perfil", IT: "Profilo", PT: "Perfil", NL: "Profiel", PL: "Profil", RU: "Профиль", JA: "プロフィール", ZH: "个人资料", KO: "프로필", AR: "الملف الشخصي", TR: "Profil", SV: "Profil", DA: "Profil", FI: "Profiili", NO: "Profil", CS: "Profil", EL: "Προφίλ", HU: "Profil", RO: "Profil", SK: "Profil", BG: "Профил", UK: "Профіль", ID: "Profil" },
  "tabs.training": { FR: "Formation", EN: "Training", DE: "Schulung", ES: "Formación", IT: "Formazione", PT: "Treinamento", NL: "Training", PL: "Szkolenie", RU: "Обучение", JA: "トレーニング", ZH: "培训", KO: "교육", AR: "التدريب", TR: "Eğitim", SV: "Utbildning", DA: "Træning", FI: "Koulutus", NO: "Opplæring", CS: "Školení", EL: "Εκπαίδευση", HU: "Képzés", RO: "Instruire", SK: "Školenie", BG: "Обучение", UK: "Навчання", ID: "Pelatihan" },
  "tabs.assessment": { FR: "Évaluation", EN: "Assessment", DE: "Bewertung", ES: "Evaluación", IT: "Valutazione", PT: "Avaliação", NL: "Beoordeling", PL: "Ocena", RU: "Оценка", JA: "評価", ZH: "评估", KO: "평가", AR: "التقييم", TR: "Değerlendirme", SV: "Bedömning", DA: "Vurdering", FI: "Arviointi", NO: "Vurdering", CS: "Hodnocení", EL: "Αξιολόγηση", HU: "Értékelés", RO: "Evaluare", SK: "Hodnotenie", BG: "Оценка", UK: "Оцінка", ID: "Penilaian" },
  
  // PERSONS
  "persons.name": { FR: "Nom", EN: "Name", DE: "Name", ES: "Nombre", IT: "Nome", PT: "Nome", NL: "Naam", PL: "Nazwa", RU: "Имя", JA: "名前", ZH: "名称", KO: "이름", AR: "الاسم", TR: "Ad", SV: "Namn", DA: "Navn", FI: "Nimi", NO: "Navn", CS: "Jméno", EL: "Όνομα", HU: "Név", RO: "Nume", SK: "Meno", BG: "Име", UK: "Ім'я", ID: "Nama" },
  "persons.email": { FR: "Email", EN: "Email", DE: "E-Mail", ES: "Correo", IT: "Email", PT: "E-mail", NL: "E-mail", PL: "Email", RU: "Эл. почта", JA: "メール", ZH: "电子邮件", KO: "이메일", AR: "البريد الإلكتروني", TR: "E-posta", SV: "E-post", DA: "E-mail", FI: "Sähköposti", NO: "E-post", CS: "E-mail", EL: "Email", HU: "E-mail", RO: "Email", SK: "E-mail", BG: "Имейл", UK: "Ел. пошта", ID: "Email" },
  "persons.position": { FR: "Poste", EN: "Position", DE: "Position", ES: "Puesto", IT: "Posizione", PT: "Cargo", NL: "Functie", PL: "Stanowisko", RU: "Должность", JA: "役職", ZH: "职位", KO: "직위", AR: "المنصب", TR: "Pozisyon", SV: "Position", DA: "Stilling", FI: "Asema", NO: "Stilling", CS: "Pozice", EL: "Θέση", HU: "Pozíció", RO: "Poziție", SK: "Pozícia", BG: "Позиция", UK: "Посада", ID: "Posisi" },
  "persons.department": { FR: "Service", EN: "Department", DE: "Abteilung", ES: "Departamento", IT: "Dipartimento", PT: "Departamento", NL: "Afdeling", PL: "Dział", RU: "Отдел", JA: "部門", ZH: "部门", KO: "부서", AR: "القسم", TR: "Departman", SV: "Avdelning", DA: "Afdeling", FI: "Osasto", NO: "Avdeling", CS: "Oddělení", EL: "Τμήμα", HU: "Osztály", RO: "Departament", SK: "Oddelenie", BG: "Отдел", UK: "Відділ", ID: "Departemen" },
  "persons.level": { FR: "Niv.", EN: "Lvl.", DE: "Stufe", ES: "Niv.", IT: "Liv.", PT: "Nív.", NL: "Niv.", PL: "Poz.", RU: "Ур.", JA: "Lv.", ZH: "等级", KO: "레벨", AR: "المستوى", TR: "Svye", SV: "Nivå", DA: "Niv.", FI: "Taso", NO: "Nivå", CS: "Úr.", EL: "Επ.", HU: "Szint", RO: "Niv.", SK: "Úr.", BG: "Ниво", UK: "Рів.", ID: "Level" },
  "persons.manager": { FR: "Responsable", EN: "Manager", DE: "Vorgesetzter", ES: "Responsable", IT: "Responsabile", PT: "Gerente", NL: "Manager", PL: "Kierownik", RU: "Руководитель", JA: "マネージャー", ZH: "经理", KO: "관리자", AR: "المدير", TR: "Yönetici", SV: "Chef", DA: "Leder", FI: "Esimies", NO: "Leder", CS: "Vedoucí", EL: "Διευθυντής", HU: "Vezető", RO: "Manager", SK: "Vedúci", BG: "Мениджър", UK: "Керівник", ID: "Manajer" },
  "persons.actions": { FR: "Actions", EN: "Actions", DE: "Aktionen", ES: "Acciones", IT: "Azioni", PT: "Ações", NL: "Acties", PL: "Akcje", RU: "Действия", JA: "アクション", ZH: "操作", KO: "작업", AR: "الإجراءات", TR: "İşlemler", SV: "Åtgärder", DA: "Handlinger", FI: "Toiminnot", NO: "Handlinger", CS: "Akce", EL: "Ενέργειες", HU: "Műveletek", RO: "Acțiuni", SK: "Akcie", BG: "Действия", UK: "Дії", ID: "Tindakan" },
  "persons.addPerson": { FR: "Ajouter une personne", EN: "Add a person", DE: "Person hinzufügen", ES: "Añadir una persona", IT: "Aggiungi una persona", PT: "Adicionar uma pessoa", NL: "Persoon toevoegen", PL: "Dodaj osobę", RU: "Добавить человека", JA: "人物を追加", ZH: "添加人员", KO: "사람 추가", AR: "إضافة شخص", TR: "Kişi Ekle", SV: "Lägg till person", DA: "Tilføj person", FI: "Lisää henkilö", NO: "Legg til person", CS: "Přidat osobu", EL: "Προσθήκη ατόμου", HU: "Személy hozzáadása", RO: "Adaugă o persoană", SK: "Pridať osobu", BG: "Добавяне на човек", UK: "Додати людину", ID: "Tambah orang" },
  "persons.noPerson": { FR: "Aucune personne dans ce site", EN: "No person in this site", DE: "Keine Person", ES: "Sin personas", IT: "Nessuna persona", PT: "Nenhuma pessoa", NL: "Geen persoon", PL: "Brak osób", RU: "Нет людей", JA: "人物がいません", ZH: "没有人员", KO: "사람이 없습니다", AR: "لا يوجد أشخاص", TR: "Kimse yok", SV: "Ingen person", DA: "Ingen person", FI: "Ei henkilöitä", NO: "Ingen person", CS: "Žádná osoba", EL: "Κανένα άτομο", HU: "Nincs személy", RO: "Nicio persoană", SK: "Žiadna osoba", BG: "Няма хора", UK: "Немає людей", ID: "Tidak ada orang" },
  "persons.useAddButton": { FR: "Utilisez le bouton \"Ajouter une personne\" ci-dessus", EN: "Use the \"Add a person\" button above", DE: "Verwenden Sie die Schaltfläche oben", ES: "Use el botón de arriba", IT: "Usa il pulsante sopra", PT: "Use o botão acima", NL: "Gebruik de knop hierboven", PL: "Użyj przycisku powyżej", RU: "Используйте кнопку выше", JA: "上のボタンを使用してください", ZH: "请使用上方按钮", KO: "위의 버튼을 사용하세요", AR: "استخدم الزر أعلاه", TR: "Yukarıdaki düğmeyi kullanın", SV: "Använd knappen ovan", DA: "Brug knappen ovenfor", FI: "Käytä yllä olevaa painiketta", NO: "Bruk knappen over", CS: "Použijte tlačítko výše", EL: "Χρησιμοποιήστε το κουμπί παραπάνω", HU: "Használja a fenti gombot", RO: "Folosiți butonul de mai sus", SK: "Použite tlačidlo vyššie", BG: "Използвайте бутона по-горе", UK: "Використовуйте кнопку вище", ID: "Gunakan tombol di atas" },
  "persons.fullName": { FR: "Nom complet", EN: "Full name", DE: "Vollständiger Name", ES: "Nombre completo", IT: "Nome completo", PT: "Nome completo", NL: "Volledige naam", PL: "Pełna nazwa", RU: "Полное имя", JA: "フルネーム", ZH: "全名", KO: "전체 이름", AR: "الاسم الكامل", TR: "Tam ad", SV: "Fullständigt namn", DA: "Fulde navn", FI: "Koko nimi", NO: "Fullt navn", CS: "Celé jméno", EL: "Πλήρες όνομα", HU: "Teljes név", RO: "Nume complet", SK: "Celé meno", BG: "Пълно име", UK: "Повне ім'я", ID: "Nama lengkap" },
  "persons.none": { FR: "Aucun", EN: "None", DE: "Keiner", ES: "Ninguno", IT: "Nessuno", PT: "Nenhum", NL: "Geen", PL: "Brak", RU: "Нет", JA: "なし", ZH: "无", KO: "없음", AR: "لا يوجد", TR: "Yok", SV: "Ingen", DA: "Ingen", FI: "Ei mitään", NO: "Ingen", CS: "Žádný", EL: "Κανένας", HU: "Nincs", RO: "Niciunul", SK: "Žiadny", BG: "Няма", UK: "Немає", ID: "Tidak ada" },
  "persons.topLevel": { FR: "personne au sommet", EN: "top level person", DE: "oberste Ebene", ES: "nivel superior", IT: "livello superiore", PT: "nível superior", NL: "topniveau", PL: "najwyższy poziom", RU: "высший уровень", JA: "トップレベル", ZH: "最高级别", KO: "최상위", AR: "المستوى الأعلى", TR: "üst düzey", SV: "toppnivå", DA: "topniveau", FI: "ylimmän tason", NO: "toppnivå", CS: "nejvyšší úroveň", EL: "ανώτατο επίπεδο", HU: "legfelső szint", RO: "nivel superior", SK: "najvyššia úroveň", BG: "най-високо ниво", UK: "найвищий рівень", ID: "tingkat atas" },
  
  // SITES
  "sites.noSites": { FR: "Aucun site créé", EN: "No sites created", DE: "Keine Websites erstellt", ES: "No hay sitios", IT: "Nessun sito", PT: "Nenhum site", NL: "Geen sites", PL: "Brak stron", RU: "Нет сайтов", JA: "サイトがありません", ZH: "没有网站", KO: "사이트 없음", AR: "لا توجد مواقع", TR: "Site yok", SV: "Inga webbplatser", DA: "Ingen sider", FI: "Ei sivustoja", NO: "Ingen nettsteder", CS: "Žádné weby", EL: "Δεν υπάρχουν ιστοσελίδες", HU: "Nincsenek webhelyek", RO: "Niciun site", SK: "Žiadne stránky", BG: "Няма сайтове", UK: "Немає сайтів", ID: "Tidak ada situs" },
  "sites.createFirst": { FR: "Créez votre premier site d'accompagnement IA", EN: "Create your first AI coaching site", DE: "Erstellen Sie Ihre erste KI-Website", ES: "Cree su primer sitio de IA", IT: "Crea il tuo primo sito IA", PT: "Crie seu primeiro site de IA", NL: "Maak uw eerste AI-site", PL: "Utwórz swoją pierwszą stronę AI", RU: "Создайте свой первый AI-сайт", JA: "最初のAIサイトを作成", ZH: "创建您的第一个AI网站", KO: "첫 번째 AI 사이트 만들기", AR: "أنشئ أول موقع AI", TR: "İlk AI sitenizi oluşturun", SV: "Skapa din första AI-webbplats", DA: "Opret dit første AI-site", FI: "Luo ensimmäinen AI-sivustosi", NO: "Opprett ditt første AI-nettsted", CS: "Vytvořte svůj první AI web", EL: "Δημιουργήστε τον πρώτο σας ιστότοπο AI", HU: "Hozza létre első AI webhelyét", RO: "Creați primul site AI", SK: "Vytvorte svoju prvú AI stránku", BG: "Създайте първия си AI сайт", UK: "Створіть свій перший AI-сайт", ID: "Buat situs AI pertama Anda" },
  "sites.createSite": { FR: "Créer un site", EN: "Create a site", DE: "Website erstellen", ES: "Crear un sitio", IT: "Crea un sito", PT: "Criar um site", NL: "Site maken", PL: "Utwórz stronę", RU: "Создать сайт", JA: "サイトを作成", ZH: "创建网站", KO: "사이트 만들기", AR: "إنشاء موقع", TR: "Site Oluştur", SV: "Skapa webbplats", DA: "Opret side", FI: "Luo sivusto", NO: "Opprett nettsted", CS: "Vytvořit web", EL: "Δημιουργία ιστοσελίδας", HU: "Webhely létrehozása", RO: "Creează un site", SK: "Vytvoriť stránku", BG: "Създай сайт", UK: "Створити сайт", ID: "Buat situs" },
  "sites.siteName": { FR: "Nom du site", EN: "Site name", DE: "Website-Name", ES: "Nombre del sitio", IT: "Nome del sito", PT: "Nome do site", NL: "Sitenaam", PL: "Nazwa strony", RU: "Название сайта", JA: "サイト名", ZH: "网站名称", KO: "사이트 이름", AR: "اسم الموقع", TR: "Site adı", SV: "Webbplatsnamn", DA: "Sidenavn", FI: "Sivuston nimi", NO: "Nettstedsnavn", CS: "Název webu", EL: "Όνομα ιστοσελίδας", HU: "Webhely neve", RO: "Numele site-ului", SK: "Názov stránky", BG: "Име на сайта", UK: "Назва сайту", ID: "Nama situs" },
  "sites.siteDescription": { FR: "Description", EN: "Description", DE: "Beschreibung", ES: "Descripción", IT: "Descrizione", PT: "Descrição", NL: "Beschrijving", PL: "Opis", RU: "Описание", JA: "説明", ZH: "描述", KO: "설명", AR: "الوصف", TR: "Açıklama", SV: "Beskrivning", DA: "Beskrivelse", FI: "Kuvaus", NO: "Beskrivelse", CS: "Popis", EL: "Περιγραφή", HU: "Leírás", RO: "Descriere", SK: "Popis", BG: "Описание", UK: "Опис", ID: "Deskripsi" },
  "sites.published": { FR: "Publié", EN: "Published", DE: "Veröffentlicht", ES: "Publicado", IT: "Pubblicato", PT: "Publicado", NL: "Gepubliceerd", PL: "Opublikowany", RU: "Опубликовано", JA: "公開済み", ZH: "已发布", KO: "게시됨", AR: "تم النشر", TR: "Yayınlandı", SV: "Publicerad", DA: "Publiceret", FI: "Julkaistu", NO: "Publisert", CS: "Publikováno", EL: "Δημοσιευμένο", HU: "Közzétéve", RO: "Publicat", SK: "Publikované", BG: "Публикувано", UK: "Опубліковано", ID: "Diterbitkan" },
  "sites.draft": { FR: "Brouillon", EN: "Draft", DE: "Entwurf", ES: "Borrador", IT: "Bozza", PT: "Rascunho", NL: "Concept", PL: "Szkic", RU: "Черновик", JA: "下書き", ZH: "草稿", KO: "초안", AR: "مسودة", TR: "Taslak", SV: "Utkast", DA: "Kladde", FI: "Luonnos", NO: "Utkast", CS: "Koncept", EL: "Πρόχειρο", HU: "Piszkozat", RO: "Ciornă", SK: "Koncept", BG: "Чернова", UK: "Чернетка", ID: "Draf" },
  
  // COMMON
  "common.loading": { FR: "Chargement...", EN: "Loading...", DE: "Laden...", ES: "Cargando...", IT: "Caricamento...", PT: "Carregando...", NL: "Laden...", PL: "Ładowanie...", RU: "Загрузка...", JA: "読み込み中...", ZH: "加载中...", KO: "로딩 중...", AR: "جار التحميل...", TR: "Yükleniyor...", SV: "Laddar...", DA: "Indlæser...", FI: "Ladataan...", NO: "Laster...", CS: "Načítání...", EL: "Φόρτωση...", HU: "Betöltés...", RO: "Se încarcă...", SK: "Načítava sa...", BG: "Зареждане...", UK: "Завантаження...", ID: "Memuat..." },
  "common.error": { FR: "Erreur", EN: "Error", DE: "Fehler", ES: "Error", IT: "Errore", PT: "Erro", NL: "Fout", PL: "Błąd", RU: "Ошибка", JA: "エラー", ZH: "错误", KO: "오류", AR: "خطأ", TR: "Hata", SV: "Fel", DA: "Fejl", FI: "Virhe", NO: "Feil", CS: "Chyba", EL: "Σφάλμα", HU: "Hiba", RO: "Eroare", SK: "Chyba", BG: "Грешка", UK: "Помилка", ID: "Kesalahan" },
  "common.success": { FR: "Succès", EN: "Success", DE: "Erfolg", ES: "Éxito", IT: "Successo", PT: "Sucesso", NL: "Succes", PL: "Sukces", RU: "Успех", JA: "成功", ZH: "成功", KO: "성공", AR: "نجاح", TR: "Başarılı", SV: "Framgång", DA: "Succes", FI: "Onnistui", NO: "Suksess", CS: "Úspěch", EL: "Επιτυχία", HU: "Siker", RO: "Succes", SK: "Úspech", BG: "Успех", UK: "Успіх", ID: "Sukses" },
  "common.save": { FR: "Enregistrer", EN: "Save", DE: "Speichern", ES: "Guardar", IT: "Salva", PT: "Salvar", NL: "Opslaan", PL: "Zapisz", RU: "Сохранить", JA: "保存", ZH: "保存", KO: "저장", AR: "حفظ", TR: "Kaydet", SV: "Spara", DA: "Gem", FI: "Tallenna", NO: "Lagre", CS: "Uložit", EL: "Αποθήκευση", HU: "Mentés", RO: "Salvare", SK: "Uložiť", BG: "Запази", UK: "Зберегти", ID: "Simpan" },
  "common.cancel": { FR: "Annuler", EN: "Cancel", DE: "Abbrechen", ES: "Cancelar", IT: "Annulla", PT: "Cancelar", NL: "Annuleren", PL: "Anuluj", RU: "Отмена", JA: "キャンセル", ZH: "取消", KO: "취소", AR: "إلغاء", TR: "İptal", SV: "Avbryt", DA: "Annuller", FI: "Peruuta", NO: "Avbryt", CS: "Zrušit", EL: "Ακύρωση", HU: "Mégse", RO: "Anulare", SK: "Zrušiť", BG: "Отказ", UK: "Скасувати", ID: "Batal" },
  "common.delete": { FR: "Supprimer", EN: "Delete", DE: "Löschen", ES: "Eliminar", IT: "Elimina", PT: "Excluir", NL: "Verwijderen", PL: "Usuń", RU: "Удалить", JA: "削除", ZH: "删除", KO: "삭제", AR: "حذف", TR: "Sil", SV: "Ta bort", DA: "Slet", FI: "Poista", NO: "Slett", CS: "Smazat", EL: "Διαγραφή", HU: "Törlés", RO: "Ștergere", SK: "Odstrániť", BG: "Изтриване", UK: "Видалити", ID: "Hapus" },
  "common.edit": { FR: "Modifier", EN: "Edit", DE: "Bearbeiten", ES: "Editar", IT: "Modifica", PT: "Editar", NL: "Bewerken", PL: "Edytuj", RU: "Редактировать", JA: "編集", ZH: "编辑", KO: "편집", AR: "تعديل", TR: "Düzenle", SV: "Redigera", DA: "Rediger", FI: "Muokkaa", NO: "Rediger", CS: "Upravit", EL: "Επεξεργασία", HU: "Szerkesztés", RO: "Editare", SK: "Upraviť", BG: "Редактиране", UK: "Редагувати", ID: "Edit" },
  "common.add": { FR: "Ajouter", EN: "Add", DE: "Hinzufügen", ES: "Añadir", IT: "Aggiungi", PT: "Adicionar", NL: "Toevoegen", PL: "Dodaj", RU: "Добавить", JA: "追加", ZH: "添加", KO: "추가", AR: "إضافة", TR: "Ekle", SV: "Lägg till", DA: "Tilføj", FI: "Lisää", NO: "Legg til", CS: "Přidat", EL: "Προσθήκη", HU: "Hozzáadás", RO: "Adaugă", SK: "Pridať", BG: "Добави", UK: "Додати", ID: "Tambah" },
  "common.close": { FR: "Fermer", EN: "Close", DE: "Schließen", ES: "Cerrar", IT: "Chiudi", PT: "Fechar", NL: "Sluiten", PL: "Zamknij", RU: "Закрыть", JA: "閉じる", ZH: "关闭", KO: "닫기", AR: "إغلاق", TR: "Kapat", SV: "Stäng", DA: "Luk", FI: "Sulje", NO: "Lukk", CS: "Zavřít", EL: "Κλείσιμο", HU: "Bezárás", RO: "Închide", SK: "Zavrieť", BG: "Затвори", UK: "Закрити", ID: "Tutup" },
  "common.yes": { FR: "Oui", EN: "Yes", DE: "Ja", ES: "Sí", IT: "Sì", PT: "Sim", NL: "Ja", PL: "Tak", RU: "Да", JA: "はい", ZH: "是", KO: "예", AR: "نعم", TR: "Evet", SV: "Ja", DA: "Ja", FI: "Kyllä", NO: "Ja", CS: "Ano", EL: "Ναι", HU: "Igen", RO: "Da", SK: "Áno", BG: "Да", UK: "Так", ID: "Ya" },
  "common.no": { FR: "Non", EN: "No", DE: "Nein", ES: "No", IT: "No", PT: "Não", NL: "Nee", PL: "Nie", RU: "Нет", JA: "いいえ", ZH: "否", KO: "아니오", AR: "لا", TR: "Hayır", SV: "Nej", DA: "Nej", FI: "Ei", NO: "Nei", CS: "Ne", EL: "Όχι", HU: "Nem", RO: "Nu", SK: "Nie", BG: "Не", UK: "Ні", ID: "Tidak" },
  "common.chooseLanguage": { FR: "Choisir la langue", EN: "Choose language", DE: "Sprache wählen", ES: "Elegir idioma", IT: "Scegli la lingua", PT: "Escolher idioma", NL: "Taal kiezen", PL: "Wybierz język", RU: "Выбрать язык", JA: "言語を選択", ZH: "选择语言", KO: "언어 선택", AR: "اختر اللغة", TR: "Dil seçin", SV: "Välj språk", DA: "Vælg sprog", FI: "Valitse kieli", NO: "Velg språk", CS: "Vybrat jazyk", EL: "Επιλέξτε γλώσσα", HU: "Nyelv kiválasztása", RO: "Alege limba", SK: "Vybrať jazyk", BG: "Изберете език", UK: "Вибрати мову", ID: "Pilih bahasa" },
  "common.siteLanguage": { FR: "Langue du contenu", EN: "Content language", DE: "Inhaltssprache", ES: "Idioma del contenido", IT: "Lingua del contenuto", PT: "Idioma do conteúdo", NL: "Taal van inhoud", PL: "Język treści", RU: "Язык контента", JA: "コンテンツ言語", ZH: "内容语言", KO: "콘텐츠 언어", AR: "لغة المحتوى", TR: "İçerik dili", SV: "Innehållsspråk", DA: "Indholdssprog", FI: "Sisältökieli", NO: "Innholdsspråk", CS: "Jazyk obsahu", EL: "Γλώσσα περιεχομένου", HU: "Tartalom nyelve", RO: "Limba conținutului", SK: "Jazyk obsahu", BG: "Език на съдържанието", UK: "Мова контенту", ID: "Bahasa konten" },
  "common.siteLanguageDescription": { FR: "Langue utilisée pour le contenu de ce site", EN: "Language used for this site's content", DE: "Sprache für den Inhalt", ES: "Idioma para el contenido", IT: "Lingua per il contenuto", PT: "Idioma para o conteúdo", NL: "Taal voor de inhoud", PL: "Język dla treści", RU: "Язык для контента", JA: "コンテンツの言語", ZH: "内容的语言", KO: "콘텐츠 언어", AR: "لغة المحتوى", TR: "İçerik dili", SV: "Innehållsspråk", DA: "Indholdssprog", FI: "Sisältökieli", NO: "Innholdsspråk", CS: "Jazyk obsahu", EL: "Γλώσσα περιεχομένου", HU: "Tartalom nyelve", RO: "Limba conținutului", SK: "Jazyk obsahu", BG: "Език на съдържанието", UK: "Мова контенту", ID: "Bahasa konten" },
  "common.required": { FR: "Requis", EN: "Required", DE: "Erforderlich", ES: "Requerido", IT: "Richiesto", PT: "Obrigatório", NL: "Vereist", PL: "Wymagane", RU: "Обязательно", JA: "必須", ZH: "必填", KO: "필수", AR: "مطلوب", TR: "Gerekli", SV: "Obligatoriskt", DA: "Påkrævet", FI: "Pakollinen", NO: "Påkrevd", CS: "Povinné", EL: "Απαιτείται", HU: "Kötelező", RO: "Obligatoriu", SK: "Povinné", BG: "Задължително", UK: "Обов'язково", ID: "Wajib" },
  
  // ORGANIZATION
  "org.title": { FR: "Organigramme", EN: "Organization chart", DE: "Organigramm", ES: "Organigrama", IT: "Organigramma", PT: "Organograma", NL: "Organigram", PL: "Schemat organizacyjny", RU: "Организационная схема", JA: "組織図", ZH: "组织结构图", KO: "조직도", AR: "الهيكل التنظيمي", TR: "Organizasyon şeması", SV: "Organisationsschema", DA: "Organisationsdiagram", FI: "Organisaatiokaavio", NO: "Organisasjonskart", CS: "Organizační schéma", EL: "Οργανόγραμμα", HU: "Szervezeti ábra", RO: "Organigramă", SK: "Organizačná schéma", BG: "Организационна схема", UK: "Організаційна схема", ID: "Bagan organisasi" },
  "org.noPersons": { FR: "Aucune personne dans l'organigramme", EN: "No person in the organization chart", DE: "Keine Person im Organigramm", ES: "Sin personas en el organigrama", IT: "Nessuna persona nell'organigramma", PT: "Nenhuma pessoa no organograma", NL: "Geen persoon in het organigram", PL: "Brak osób w schemacie", RU: "Нет людей в схеме", JA: "組織図に人物がいません", ZH: "组织结构图中没有人员", KO: "조직도에 사람이 없습니다", AR: "لا يوجد أشخاص", TR: "Kimse yok", SV: "Ingen person i schemat", DA: "Ingen person i diagrammet", FI: "Ei henkilöitä kaaviossa", NO: "Ingen person i kartet", CS: "Žádná osoba ve schématu", EL: "Κανένα άτομο", HU: "Nincs személy", RO: "Nicio persoană", SK: "Žiadna osoba", BG: "Няма хора", UK: "Немає людей", ID: "Tidak ada orang" },
  "org.addPersonsFirst": { FR: "Ajoutez des personnes dans l'onglet Équipe", EN: "Add persons in the Team tab", DE: "Fügen Sie Personen im Team-Tab hinzu", ES: "Añade personas en la pestaña Equipo", IT: "Aggiungi persone nella scheda Team", PT: "Adicione pessoas na aba Equipe", NL: "Voeg personen toe in het Team-tabblad", PL: "Dodaj osoby w zakładce Zespół", RU: "Добавьте людей во вкладке Команда", JA: "チームタブで人物を追加", ZH: "在团队选项卡中添加人员", KO: "팀 탭에서 사람 추가", AR: "أضف أشخاصًا في علامة الفريق", TR: "Ekip sekmesine kişi ekleyin", SV: "Lägg till personer i Team-fliken", DA: "Tilføj personer i Team-fanen", FI: "Lisää henkilöitä Tiimi-välilehdelle", NO: "Legg til personer i Team-fanen", CS: "Přidejte osoby na záložce Tým", EL: "Προσθέστε άτομα στην καρτέλα Ομάδα", HU: "Adjon hozzá személyeket a Csapat fülön", RO: "Adăugați persoane în fila Echipă", SK: "Pridajte osoby na karte Tím", BG: "Добавете хора в раздела Екип", UK: "Додайте людей у вкладці Команда", ID: "Tambahkan orang di tab Tim" },
  
  // PROFILE
  "profile.selectPerson": { FR: "Sélectionnez une personne", EN: "Select a person", DE: "Wählen Sie eine Person", ES: "Seleccione una persona", IT: "Seleziona una persona", PT: "Selecione uma pessoa", NL: "Selecteer een persoon", PL: "Wybierz osobę", RU: "Выберите человека", JA: "人物を選択", ZH: "选择一个人", KO: "사람 선택", AR: "اختر شخصًا", TR: "Bir kişi seçin", SV: "Välj en person", DA: "Vælg en person", FI: "Valitse henkilö", NO: "Velg en person", CS: "Vyberte osobu", EL: "Επιλέξτε ένα άτομο", HU: "Válasszon egy személyt", RO: "Selectați o persoană", SK: "Vyberte osobu", BG: "Изберете човек", UK: "Виберіть людину", ID: "Pilih orang" },
  "profile.noPersonSelected": { FR: "Cliquez sur une personne pour voir son profil", EN: "Click on a person to view their profile", DE: "Klicken Sie auf eine Person", ES: "Haga clic en una persona", IT: "Clicca su una persona", PT: "Clique em uma pessoa", NL: "Klik op een persoon", PL: "Kliknij osobę", RU: "Нажмите на человека", JA: "人物をクリック", ZH: "点击人员查看", KO: "사람을 클릭", AR: "انقر على شخص", TR: "Bir kişiye tıklayın", SV: "Klicka på en person", DA: "Klik på en person", FI: "Napsauta henkilöä", NO: "Klikk på en person", CS: "Klikněte na osobu", EL: "Κάντε κλικ σε ένα άτομο", HU: "Kattintson egy személyre", RO: "Faceți clic pe o persoană", SK: "Kliknite na osobu", BG: "Кликнете върху човек", UK: "Натисніть на людину", ID: "Klik orang" },
  "profile.aiLevel": { FR: "Niveau IA", EN: "AI Level", DE: "KI-Stufe", ES: "Nivel IA", IT: "Livello IA", PT: "Nível IA", NL: "AI-niveau", PL: "Poziom AI", RU: "Уровень ИИ", JA: "AIレベル", ZH: "AI等级", KO: "AI 레벨", AR: "مستوى الذكاء الاصطناعي", TR: "AI Seviyesi", SV: "AI-nivå", DA: "AI-niveau", FI: "AI-taso", NO: "AI-nivå", CS: "Úroveň AI", EL: "Επίπεδο AI", HU: "AI szint", RO: "Nivel AI", SK: "Úroveň AI", BG: "Ниво на AI", UK: "Рівень ШІ", ID: "Level AI" },
  
  // PLACEHOLDERS (textes indicatifs dans les champs)
  "placeholder.enterName": { FR: "Entrez le nom...", EN: "Enter name...", DE: "Name eingeben...", ES: "Ingrese el nombre...", IT: "Inserisci il nome...", PT: "Digite o nome...", NL: "Voer naam in...", PL: "Wprowadź nazwę...", RU: "Введите имя...", JA: "名前を入力...", ZH: "输入名称...", KO: "이름 입력...", AR: "أدخل الاسم...", TR: "Adı girin...", SV: "Ange namn...", DA: "Indtast navn...", FI: "Syötä nimi...", NO: "Skriv inn navn...", CS: "Zadejte jméno...", EL: "Εισάγετε όνομα...", HU: "Adja meg a nevet...", RO: "Introduceți numele...", SK: "Zadajte meno...", BG: "Въведете име...", UK: "Введіть ім'я...", ID: "Masukkan nama..." },
  "placeholder.enterEmail": { FR: "Entrez l'email...", EN: "Enter email...", DE: "E-Mail eingeben...", ES: "Ingrese el correo...", IT: "Inserisci l'email...", PT: "Digite o e-mail...", NL: "Voer e-mail in...", PL: "Wprowadź email...", RU: "Введите email...", JA: "メールを入力...", ZH: "输入邮箱...", KO: "이메일 입력...", AR: "أدخل البريد...", TR: "E-posta girin...", SV: "Ange e-post...", DA: "Indtast e-mail...", FI: "Syötä sähköposti...", NO: "Skriv inn e-post...", CS: "Zadejte e-mail...", EL: "Εισάγετε email...", HU: "Adja meg az e-mailt...", RO: "Introduceți email-ul...", SK: "Zadajte e-mail...", BG: "Въведете имейл...", UK: "Введіть email...", ID: "Masukkan email..." },
  "placeholder.enterPosition": { FR: "Entrez le poste...", EN: "Enter position...", DE: "Position eingeben...", ES: "Ingrese el puesto...", IT: "Inserisci la posizione...", PT: "Digite o cargo...", NL: "Voer functie in...", PL: "Wprowadź stanowisko...", RU: "Введите должность...", JA: "役職を入力...", ZH: "输入职位...", KO: "직위 입력...", AR: "أدخل المنصب...", TR: "Pozisyon girin...", SV: "Ange position...", DA: "Indtast stilling...", FI: "Syötä asema...", NO: "Skriv inn stilling...", CS: "Zadejte pozici...", EL: "Εισάγετε θέση...", HU: "Adja meg a pozíciót...", RO: "Introduceți poziția...", SK: "Zadajte pozíciu...", BG: "Въведете позиция...", UK: "Введіть посаду...", ID: "Masukkan posisi..." },
  "placeholder.enterDepartment": { FR: "Entrez le service...", EN: "Enter department...", DE: "Abteilung eingeben...", ES: "Ingrese el departamento...", IT: "Inserisci il dipartimento...", PT: "Digite o departamento...", NL: "Voer afdeling in...", PL: "Wprowadź dział...", RU: "Введите отдел...", JA: "部門を入力...", ZH: "输入部门...", KO: "부서 입력...", AR: "أدخل القسم...", TR: "Departman girin...", SV: "Ange avdelning...", DA: "Indtast afdeling...", FI: "Syötä osasto...", NO: "Skriv inn avdeling...", CS: "Zadejte oddělení...", EL: "Εισάγετε τμήμα...", HU: "Adja meg az osztályt...", RO: "Introduceți departamentul...", SK: "Zadajte oddelenie...", BG: "Въведете отдел...", UK: "Введіть відділ...", ID: "Masukkan departemen..." },
  "placeholder.enterSiteName": { FR: "Entrez le nom du site...", EN: "Enter site name...", DE: "Website-Namen eingeben...", ES: "Ingrese el nombre del sitio...", IT: "Inserisci il nome del sito...", PT: "Digite o nome do site...", NL: "Voer sitenaam in...", PL: "Wprowadź nazwę strony...", RU: "Введите название сайта...", JA: "サイト名を入力...", ZH: "输入网站名称...", KO: "사이트 이름 입력...", AR: "أدخل اسم الموقع...", TR: "Site adı girin...", SV: "Ange webbplatsnamn...", DA: "Indtast sidenavn...", FI: "Syötä sivuston nimi...", NO: "Skriv inn nettstedsnavn...", CS: "Zadejte název webu...", EL: "Εισάγετε όνομα ιστοσελίδας...", HU: "Adja meg a webhely nevét...", RO: "Introduceți numele site-ului...", SK: "Zadajte názov stránky...", BG: "Въведете име на сайта...", UK: "Введіть назву сайту...", ID: "Masukkan nama situs..." },
  "placeholder.enterDescription": { FR: "Entrez une description...", EN: "Enter description...", DE: "Beschreibung eingeben...", ES: "Ingrese una descripción...", IT: "Inserisci una descrizione...", PT: "Digite uma descrição...", NL: "Voer beschrijving in...", PL: "Wprowadź opis...", RU: "Введите описание...", JA: "説明を入力...", ZH: "输入描述...", KO: "설명 입력...", AR: "أدخل الوصف...", TR: "Açıklama girin...", SV: "Ange beskrivning...", DA: "Indtast beskrivelse...", FI: "Syötä kuvaus...", NO: "Skriv inn beskrivelse...", CS: "Zadejte popis...", EL: "Εισάγετε περιγραφή...", HU: "Adja meg a leírást...", RO: "Introduceți descrierea...", SK: "Zadajte popis...", BG: "Въведете описание...", UK: "Введіть опис...", ID: "Masukkan deskripsi..." },
  "placeholder.selectManager": { FR: "Sélectionnez un responsable...", EN: "Select a manager...", DE: "Wählen Sie einen Vorgesetzten...", ES: "Seleccione un responsable...", IT: "Seleziona un responsabile...", PT: "Selecione um gerente...", NL: "Selecteer een manager...", PL: "Wybierz kierownika...", RU: "Выберите руководителя...", JA: "マネージャーを選択...", ZH: "选择经理...", KO: "관리자 선택...", AR: "اختر مديرًا...", TR: "Yönetici seçin...", SV: "Välj chef...", DA: "Vælg leder...", FI: "Valitse esimies...", NO: "Velg leder...", CS: "Vyberte vedoucího...", EL: "Επιλέξτε διευθυντή...", HU: "Válasszon vezetőt...", RO: "Selectați un manager...", SK: "Vyberte vedúceho...", BG: "Изберете мениджър...", UK: "Виберіть керівника...", ID: "Pilih manajer..." },
  
  // TOOLTIPS (informations au survol)
  "tooltip.viewProfile": { FR: "Voir le profil", EN: "View profile", DE: "Profil anzeigen", ES: "Ver perfil", IT: "Visualizza profilo", PT: "Ver perfil", NL: "Profiel bekijken", PL: "Zobacz profil", RU: "Просмотр профиля", JA: "プロフィールを見る", ZH: "查看资料", KO: "프로필 보기", AR: "عرض الملف", TR: "Profili görüntüle", SV: "Visa profil", DA: "Se profil", FI: "Näytä profiili", NO: "Vis profil", CS: "Zobrazit profil", EL: "Προβολή προφίλ", HU: "Profil megtekintése", RO: "Vezi profilul", SK: "Zobraziť profil", BG: "Вижте профила", UK: "Переглянути профіль", ID: "Lihat profil" },
  "tooltip.editPerson": { FR: "Modifier la personne", EN: "Edit person", DE: "Person bearbeiten", ES: "Editar persona", IT: "Modifica persona", PT: "Editar pessoa", NL: "Persoon bewerken", PL: "Edytuj osobę", RU: "Редактировать человека", JA: "人物を編集", ZH: "编辑人员", KO: "사람 편집", AR: "تعديل الشخص", TR: "Kişiyi düzenle", SV: "Redigera person", DA: "Rediger person", FI: "Muokkaa henkilöä", NO: "Rediger person", CS: "Upravit osobu", EL: "Επεξεργασία ατόμου", HU: "Személy szerkesztése", RO: "Editare persoană", SK: "Upraviť osobu", BG: "Редактиране на човек", UK: "Редагувати людину", ID: "Edit orang" },
  "tooltip.deletePerson": { FR: "Supprimer la personne", EN: "Delete person", DE: "Person löschen", ES: "Eliminar persona", IT: "Elimina persona", PT: "Excluir pessoa", NL: "Persoon verwijderen", PL: "Usuń osobę", RU: "Удалить человека", JA: "人物を削除", ZH: "删除人员", KO: "사람 삭제", AR: "حذف الشخص", TR: "Kişiyi sil", SV: "Ta bort person", DA: "Slet person", FI: "Poista henkilö", NO: "Slett person", CS: "Smazat osobu", EL: "Διαγραφή ατόμου", HU: "Személy törlése", RO: "Șterge persoana", SK: "Odstrániť osobu", BG: "Изтриване на човек", UK: "Видалити людину", ID: "Hapus orang" },
  "tooltip.editSite": { FR: "Modifier le site", EN: "Edit site", DE: "Website bearbeiten", ES: "Editar sitio", IT: "Modifica sito", PT: "Editar site", NL: "Site bewerken", PL: "Edytuj stronę", RU: "Редактировать сайт", JA: "サイトを編集", ZH: "编辑网站", KO: "사이트 편집", AR: "تعديل الموقع", TR: "Siteyi düzenle", SV: "Redigera webbplats", DA: "Rediger side", FI: "Muokkaa sivustoa", NO: "Rediger nettsted", CS: "Upravit web", EL: "Επεξεργασία ιστοσελίδας", HU: "Webhely szerkesztése", RO: "Editare site", SK: "Upraviť stránku", BG: "Редактиране на сайт", UK: "Редагувати сайт", ID: "Edit situs" },
  "tooltip.deleteSite": { FR: "Supprimer le site", EN: "Delete site", DE: "Website löschen", ES: "Eliminar sitio", IT: "Elimina sito", PT: "Excluir site", NL: "Site verwijderen", PL: "Usuń stronę", RU: "Удалить сайт", JA: "サイトを削除", ZH: "删除网站", KO: "사이트 삭제", AR: "حذف الموقع", TR: "Siteyi sil", SV: "Ta bort webbplats", DA: "Slet side", FI: "Poista sivusto", NO: "Slett nettsted", CS: "Smazat web", EL: "Διαγραφή ιστοσελίδας", HU: "Webhely törlése", RO: "Șterge site-ul", SK: "Odstrániť stránku", BG: "Изтриване на сайт", UK: "Видалити сайт", ID: "Hapus situs" },
  "tooltip.duplicateSite": { FR: "Dupliquer le site", EN: "Duplicate site", DE: "Website duplizieren", ES: "Duplicar sitio", IT: "Duplica sito", PT: "Duplicar site", NL: "Site dupliceren", PL: "Duplikuj stronę", RU: "Дублировать сайт", JA: "サイトを複製", ZH: "复制网站", KO: "사이트 복제", AR: "تكرار الموقع", TR: "Siteyi çoğalt", SV: "Duplicera webbplats", DA: "Dupliker side", FI: "Kopioi sivusto", NO: "Dupliser nettsted", CS: "Duplikovat web", EL: "Αντιγραφή ιστοσελίδας", HU: "Webhely másolása", RO: "Duplicare site", SK: "Duplikovať stránku", BG: "Дублиране на сайт", UK: "Дублювати сайт", ID: "Duplikat situs" },
  "tooltip.publishSite": { FR: "Publier le site", EN: "Publish site", DE: "Website veröffentlichen", ES: "Publicar sitio", IT: "Pubblica sito", PT: "Publicar site", NL: "Site publiceren", PL: "Opublikuj stronę", RU: "Опубликовать сайт", JA: "サイトを公開", ZH: "发布网站", KO: "사이트 게시", AR: "نشر الموقع", TR: "Siteyi yayınla", SV: "Publicera webbplats", DA: "Publicer side", FI: "Julkaise sivusto", NO: "Publiser nettsted", CS: "Publikovat web", EL: "Δημοσίευση ιστοσελίδας", HU: "Webhely közzététele", RO: "Publică site-ul", SK: "Publikovať stránku", BG: "Публикуване на сайт", UK: "Опублікувати сайт", ID: "Publikasikan situs" },
  "tooltip.unpublishSite": { FR: "Dépublier le site", EN: "Unpublish site", DE: "Veröffentlichung aufheben", ES: "Despublicar sitio", IT: "Annulla pubblicazione", PT: "Despublicar site", NL: "Publicatie ongedaan maken", PL: "Cofnij publikację", RU: "Снять с публикации", JA: "公開を取り消す", ZH: "取消发布", KO: "게시 취소", AR: "إلغاء نشر الموقع", TR: "Yayından kaldır", SV: "Avpublicera", DA: "Afpublicer", FI: "Peruuta julkaisu", NO: "Avpubliser", CS: "Zrušit publikaci", EL: "Κατάργηση δημοσίευσης", HU: "Közzététel visszavonása", RO: "Anulare publicare", SK: "Zrušiť publikáciu", BG: "Отмени публикуването", UK: "Скасувати публікацію", ID: "Batalkan publikasi" },
  "tooltip.siteSettings": { FR: "Paramètres du site", EN: "Site settings", DE: "Website-Einstellungen", ES: "Configuración del sitio", IT: "Impostazioni del sito", PT: "Configurações do site", NL: "Site-instellingen", PL: "Ustawienia strony", RU: "Настройки сайта", JA: "サイト設定", ZH: "网站设置", KO: "사이트 설정", AR: "إعدادات الموقع", TR: "Site ayarları", SV: "Webbplatsinställningar", DA: "Sideindstillinger", FI: "Sivuston asetukset", NO: "Nettstedsinnstillinger", CS: "Nastavení webu", EL: "Ρυθμίσεις ιστοσελίδας", HU: "Webhely beállításai", RO: "Setări site", SK: "Nastavenia stránky", BG: "Настройки на сайта", UK: "Налаштування сайту", ID: "Pengaturan situs" },
  "tooltip.changeLanguage": { FR: "Changer la langue", EN: "Change language", DE: "Sprache ändern", ES: "Cambiar idioma", IT: "Cambia lingua", PT: "Mudar idioma", NL: "Taal wijzigen", PL: "Zmień język", RU: "Изменить язык", JA: "言語を変更", ZH: "更改语言", KO: "언어 변경", AR: "تغيير اللغة", TR: "Dili değiştir", SV: "Ändra språk", DA: "Skift sprog", FI: "Vaihda kieli", NO: "Endre språk", CS: "Změnit jazyk", EL: "Αλλαγή γλώσσας", HU: "Nyelv módosítása", RO: "Schimbare limbă", SK: "Zmeniť jazyk", BG: "Промяна на езика", UK: "Змінити мову", ID: "Ubah bahasa" },
  "tooltip.userMenu": { FR: "Menu utilisateur", EN: "User menu", DE: "Benutzermenü", ES: "Menú de usuario", IT: "Menu utente", PT: "Menu do usuário", NL: "Gebruikersmenu", PL: "Menu użytkownika", RU: "Меню пользователя", JA: "ユーザーメニュー", ZH: "用户菜单", KO: "사용자 메뉴", AR: "قائمة المستخدم", TR: "Kullanıcı menüsü", SV: "Användarmeny", DA: "Brugermenu", FI: "Käyttäjävalikko", NO: "Brukermeny", CS: "Menu uživatele", EL: "Μενού χρήστη", HU: "Felhasználói menü", RO: "Meniu utilizator", SK: "Menu používateľa", BG: "Меню на потребителя", UK: "Меню користувача", ID: "Menu pengguna" },
  "tooltip.sortAscending": { FR: "Trier par ordre croissant", EN: "Sort ascending", DE: "Aufsteigend sortieren", ES: "Ordenar ascendente", IT: "Ordina crescente", PT: "Ordenar crescente", NL: "Oplopend sorteren", PL: "Sortuj rosnąco", RU: "Сортировать по возрастанию", JA: "昇順で並べ替え", ZH: "升序排列", KO: "오름차순 정렬", AR: "ترتيب تصاعدي", TR: "Artan sırala", SV: "Sortera stigande", DA: "Sortér stigende", FI: "Lajittele nousevasti", NO: "Sorter stigende", CS: "Řadit vzestupně", EL: "Ταξινόμηση αύξουσα", HU: "Növekvő rendezés", RO: "Sortare crescătoare", SK: "Zoradiť vzostupne", BG: "Сортирай възходящо", UK: "Сортувати за зростанням", ID: "Urutkan naik" },
  "tooltip.sortDescending": { FR: "Trier par ordre décroissant", EN: "Sort descending", DE: "Absteigend sortieren", ES: "Ordenar descendente", IT: "Ordina decrescente", PT: "Ordenar decrescente", NL: "Aflopend sorteren", PL: "Sortuj malejąco", RU: "Сортировать по убыванию", JA: "降順で並べ替え", ZH: "降序排列", KO: "내림차순 정렬", AR: "ترتيب تنازلي", TR: "Azalan sırala", SV: "Sortera fallande", DA: "Sortér faldende", FI: "Lajittele laskevasti", NO: "Sorter synkende", CS: "Řadit sestupně", EL: "Ταξινόμηση φθίνουσα", HU: "Csökkenő rendezés", RO: "Sortare descrescătoare", SK: "Zoradiť zostupne", BG: "Сортирай низходящо", UK: "Сортувати за спаданням", ID: "Urutkan turun" },
  "tooltip.siteContentLanguage": { FR: "Langue du contenu du site", EN: "Site content language", DE: "Sprache des Website-Inhalts", ES: "Idioma del contenido del sitio", IT: "Lingua del contenuto del sito", PT: "Idioma do conteúdo do site", NL: "Taal van site-inhoud", PL: "Język treści strony", RU: "Язык контента сайта", JA: "サイトコンテンツの言語", ZH: "网站内容语言", KO: "사이트 콘텐츠 언어", AR: "لغة محتوى الموقع", TR: "Site içerik dili", SV: "Webbplatsinnehållsspråk", DA: "Sideindholdssprog", FI: "Sivuston sisältökieli", NO: "Nettstedsinnholdsspråk", CS: "Jazyk obsahu webu", EL: "Γλώσσα περιεχομένου ιστοσελίδας", HU: "Webhely tartalmának nyelve", RO: "Limba conținutului site-ului", SK: "Jazyk obsahu stránky", BG: "Език на съдържанието на сайта", UK: "Мова контенту сайту", ID: "Bahasa konten situs" },
  "tooltip.viewSite": { FR: "Voir le site", EN: "View site", DE: "Website anzeigen", ES: "Ver sitio", IT: "Visualizza sito", PT: "Ver site", NL: "Site bekijken", PL: "Zobacz stronę", RU: "Просмотр сайта", JA: "サイトを見る", ZH: "查看网站", KO: "사이트 보기", AR: "عرض الموقع", TR: "Siteyi görüntüle", SV: "Visa webbplats", DA: "Se side", FI: "Näytä sivusto", NO: "Vis nettsted", CS: "Zobrazit web", EL: "Προβολή ιστοσελίδας", HU: "Webhely megtekintése", RO: "Vezi site-ul", SK: "Zobraziť stránku", BG: "Вижте сайта", UK: "Переглянути сайт", ID: "Lihat situs" },
  
  // SETTINGS PANEL (Paramètres du site)
  "settings.siteSettings": { FR: "Paramètres du site", EN: "Site settings", DE: "Website-Einstellungen", ES: "Configuración del sitio", IT: "Impostazioni del sito", PT: "Configurações do site", NL: "Site-instellingen", PL: "Ustawienia strony", RU: "Настройки сайта", JA: "サイト設定", ZH: "网站设置", KO: "사이트 설정", AR: "إعدادات الموقع", TR: "Site ayarları", SV: "Webbplatsinställningar", DA: "Sideindstillinger", FI: "Sivuston asetukset", NO: "Nettstedsinnstillinger", CS: "Nastavení webu", EL: "Ρυθμίσεις ιστοσελίδας", HU: "Webhely beállításai", RO: "Setări site", SK: "Nastavenia stránky", BG: "Настройки на сайта", UK: "Налаштування сайту", ID: "Pengaturan situs" },
  "settings.generalInfo": { FR: "Informations générales", EN: "General information", DE: "Allgemeine Informationen", ES: "Información general", IT: "Informazioni generali", PT: "Informações gerais", NL: "Algemene informatie", PL: "Informacje ogólne", RU: "Общая информация", JA: "一般情報", ZH: "基本信息", KO: "일반 정보", AR: "معلومات عامة", TR: "Genel bilgiler", SV: "Allmän information", DA: "Generel information", FI: "Yleiset tiedot", NO: "Generell informasjon", CS: "Obecné informace", EL: "Γενικές πληροφορίες", HU: "Általános információk", RO: "Informații generale", SK: "Všeobecné informácie", BG: "Обща информация", UK: "Загальна інформація", ID: "Informasi umum" },
  "settings.personalization": { FR: "Personnalisation", EN: "Personalization", DE: "Personalisierung", ES: "Personalización", IT: "Personalizzazione", PT: "Personalização", NL: "Personalisatie", PL: "Personalizacja", RU: "Персонализация", JA: "パーソナライズ", ZH: "个性化", KO: "개인화", AR: "التخصيص", TR: "Kişiselleştirme", SV: "Personalisering", DA: "Personalisering", FI: "Personointi", NO: "Personalisering", CS: "Personalizace", EL: "Εξατομίκευση", HU: "Testreszabás", RO: "Personalizare", SK: "Personalizácia", BG: "Персонализация", UK: "Персоналізація", ID: "Personalisasi" },
  "settings.primaryColor": { FR: "Couleur principale", EN: "Primary color", DE: "Primärfarbe", ES: "Color primario", IT: "Colore primario", PT: "Cor primária", NL: "Primaire kleur", PL: "Kolor główny", RU: "Основной цвет", JA: "メインカラー", ZH: "主色", KO: "기본 색상", AR: "اللون الأساسي", TR: "Ana renk", SV: "Primärfärg", DA: "Primær farve", FI: "Ensisijainen väri", NO: "Primærfarge", CS: "Primární barva", EL: "Κύριο χρώμα", HU: "Elsődleges szín", RO: "Culoare primară", SK: "Primárna farba", BG: "Основен цвят", UK: "Основний колір", ID: "Warna utama" },
  "settings.secondaryColor": { FR: "Couleur secondaire", EN: "Secondary color", DE: "Sekundärfarbe", ES: "Color secundario", IT: "Colore secondario", PT: "Cor secundária", NL: "Secundaire kleur", PL: "Kolor dodatkowy", RU: "Дополнительный цвет", JA: "サブカラー", ZH: "辅色", KO: "보조 색상", AR: "اللون الثانوي", TR: "İkincil renk", SV: "Sekundärfärg", DA: "Sekundær farve", FI: "Toissijainen väri", NO: "Sekundærfarge", CS: "Sekundární barva", EL: "Δευτερεύον χρώμα", HU: "Másodlagos szín", RO: "Culoare secundară", SK: "Sekundárna farba", BG: "Вторичен цвят", UK: "Вторинний колір", ID: "Warna sekunder" },
  "settings.publishedUrl": { FR: "URL du site publié", EN: "Published site URL", DE: "Veröffentlichte URL", ES: "URL del sitio publicado", IT: "URL del sito pubblicato", PT: "URL do site publicado", NL: "Gepubliceerde URL", PL: "URL opublikowanej strony", RU: "URL опубликованного сайта", JA: "公開サイトURL", ZH: "已发布站点URL", KO: "게시된 사이트 URL", AR: "رابط الموقع المنشور", TR: "Yayınlanan site URL'si", SV: "Publicerad webbadress", DA: "Publiceret URL", FI: "Julkaistun sivuston URL", NO: "Publisert URL", CS: "URL publikovaného webu", EL: "URL δημοσιευμένου ιστοτόπου", HU: "Közzétett webhely URL", RO: "URL site publicat", SK: "URL publikovanej stránky", BG: "URL на публикувания сайт", UK: "URL опублікованого сайту", ID: "URL situs yang dipublikasi" },
};

const LANGUAGES = ["FR", "EN", "DE", "ES", "IT", "PT", "NL", "PL", "RU", "JA", "ZH", "KO", "AR", "TR", "SV", "DA", "FI", "NO", "CS", "EL", "HU", "RO", "SK", "BG", "UK", "ID"];

// POST - Insérer toutes les traductions
export async function POST() {
  try {
    let count = 0;

    for (const [key, translations] of Object.entries(TRANSLATIONS)) {
      for (const lang of LANGUAGES) {
        const value = translations[lang];
        if (!value) continue;

        // Chercher si la traduction existe déjà
        const existing = await prisma.translation.findFirst({
          where: {
            key,
            language: lang,
            type: "GLOBAL",
            siteId: null,
          },
        });

        if (existing) {
          await prisma.translation.update({
            where: { id: existing.id },
            data: { value },
          });
        } else {
          await prisma.translation.create({
            data: {
              key,
              language: lang,
              value,
              type: "GLOBAL",
            },
          });
        }
        count++;
      }
    }

    return NextResponse.json({ 
      success: true, 
      count,
      keys: Object.keys(TRANSLATIONS).length,
      languages: LANGUAGES.length,
    });
  } catch (error) {
    console.error("Error seeding translations:", error);
    return NextResponse.json({ error: "Failed to seed translations" }, { status: 500 });
  }
}
